global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: devops-evaluation-app
    metrics_path: /metrics
    static_configs:
      - targets:
          - app:8000
